export const BASE_URL = "https://www.finna.fi"
export const IMAGE_BASE_URL = "https://www.finna.fi/Cover/Show?id="
export const API_SEARCH_URL = "https://api.finna.fi/v1/search?"
export const API_RECORD_URL = "https://api.finna.fi/v1/record?id="
export const REPO_URL = "https://github.com/JesseK13241/WanhatWalokuvat"
